# Generated by Django 5.2 on 2025-05-04 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_whitelisted',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='VoterElectionWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_whitelisted', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelisted_voters', to='api.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelisted_elections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('voter', 'election')},
            },
        ),
    ]
