# Generated by Django 5.2 on 2025-05-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_is_whitelisted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectoralRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_roll', to='api.election')),
            ],
            options={
                'unique_together': {('election', 'student_id')},
            },
        ),
    ]
